AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

# Since when is whitespace a bad thing?
EmptyLinesAroundBody:
  Enabled: false

LineLength:
  Max: 100

SingleSpaceBeforeFirstArg:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AlignParameters:
  Enabled: false
